#!/usr/bin/env bash

set -e

source /etc/torproxy/internal/index.sh

TOR_PORT="$(current_socks_port)"
curl \
  -s \
  -x "socks5://127.0.0.1:${TOR_PORT}/" \
  https://check.torproject.org/api/ip | grep -q 'true' && echo "OK" || echo "FAIL"
