#!/usr/bin/env bash

set -e

source /etc/torproxy/internal/index.sh

curl \
  -s \
  -x "socks5://127.0.0.1:$(current_socks_port)" \
  https://check.torproject.org/api/ip | grep -q 'true' && echo "OK" || echo "FAIL"
