#!/bin/bash

TOR_SOCKS_PORT="$(get-socks-port)"

# kill previous gost session
if screen -list | grep -q gost; then
  screen -S gost -X quit
fi

screen -L -Logfile /var/log/gogost/gost.log -dmS gost \
  bash -c "gost -F socks5://127.0.0.1:${TOR_SOCKS_PORT} ${*}"
