#!/bin/bash

TOR_SOCKS_PORT="$(get-socks-port)"
SCREEN_NAME="gost"

# Kill previous session
if screen -list | grep -q "${SCREEN_NAME}"; then
  screen -S "${SCREEN_NAME}" -X quit
fi

screen -dmS "${SCREEN_NAME}" -h 1000 \
  bash -c "gost -F socks5://127.0.0.1:${TOR_SOCKS_PORT} ${*}"
